package me.lovelace.loveclans.gui;

public enum ClanMenuType {
    MAIN,
    MEMBERS,
    TERRITORIES,
    UPGRADES,
    PERKS,
    SETTINGS,
    DIPLOMACY,
    DIPLOMACY_SELECT,
    RELATIONS,
    CONFIRM,
    MEMBER_DETAIL,
    COLOR_PICKER,
    TERRITORY_SETTINGS,
    ROLE_SETTINGS,
    RANK_PERMISSIONS,
    CONTRACTS,
    CONTRACT_CHOICE,
    GUILDMASTER,
    RECOGNITION_CONFIRM,
    CHEST_MONEY,
    MODIFIERS,
    CASUS_BELLI,
    TRADE,
    CAMP_FORTIFY
}